# Generated by Django 5.1.6 on 2025-02-25 14:01

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('can_preview', models.BooleanField(default=False, help_text='This lesson can be previewed by anyone')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PUBLISHED', 'Published'), ('soon', 'Comming Soon'), ('DRAFT', 'Draft')], default='DRAFT', max_length=10)),
                ('position', models.IntegerField(default=0)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('video_duration', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('thumbnail', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
                ('free_preview', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
